<?php

/**
 * BasetableExample2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $field1
 * @property text $field2
 * @property enum $choice
 * @property enum $multichoice
 * @property string $imagen
 * @property boolean $checkbox
 * @property enum $radio
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method text          getField1()      Returns the current record's "field1" value
 * @method text          getField2()      Returns the current record's "field2" value
 * @method enum          getChoice()      Returns the current record's "choice" value
 * @method enum          getMultichoice() Returns the current record's "multichoice" value
 * @method string        getImagen()      Returns the current record's "imagen" value
 * @method boolean       getCheckbox()    Returns the current record's "checkbox" value
 * @method enum          getRadio()       Returns the current record's "radio" value
 * @method tableExample2 setId()          Sets the current record's "id" value
 * @method tableExample2 setField1()      Sets the current record's "field1" value
 * @method tableExample2 setField2()      Sets the current record's "field2" value
 * @method tableExample2 setChoice()      Sets the current record's "choice" value
 * @method tableExample2 setMultichoice() Sets the current record's "multichoice" value
 * @method tableExample2 setImagen()      Sets the current record's "imagen" value
 * @method tableExample2 setCheckbox()    Sets the current record's "checkbox" value
 * @method tableExample2 setRadio()       Sets the current record's "radio" value
 * 
 * @package    mdResponsive
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetableExample2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('table_example2');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('field1', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('field2', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('choice', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'value1',
              1 => 'value2',
              2 => 'value3',
             ),
             ));
        $this->hasColumn('multichoice', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'value1',
              1 => 'value2',
              2 => 'value3',
             ),
             ));
        $this->hasColumn('imagen', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('checkbox', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('radio', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'value1',
              1 => 'value2',
              2 => 'value3',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}