<?php

/**
 * BasetableExample3
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $field1
 * @property text $field2
 * @property enum $choice
 * 
 * @method integer       getId()     Returns the current record's "id" value
 * @method text          getField1() Returns the current record's "field1" value
 * @method text          getField2() Returns the current record's "field2" value
 * @method enum          getChoice() Returns the current record's "choice" value
 * @method tableExample3 setId()     Sets the current record's "id" value
 * @method tableExample3 setField1() Sets the current record's "field1" value
 * @method tableExample3 setField2() Sets the current record's "field2" value
 * @method tableExample3 setChoice() Sets the current record's "choice" value
 * 
 * @package    mdResponsive
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetableExample3 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('table_example3');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('field1', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('field2', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('choice', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'value1',
              1 => 'value2',
              2 => 'value3',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}