<?php

/**
 * tableExample2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tableExample2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tableExample2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tableExample2');
    }
}