<?php

/**
 * tableExample3Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tableExample3Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tableExample3Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tableExample3');
    }
}