<?php

/**
 * tableExample1Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tableExample1Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tableExample1Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tableExample1');
    }
}